import * as fs from "node:fs";

export interface InitOptions {
  output?: string;
}

const sampleProject = `# Text Overlay Project
# Generated by textoverlay init

project:
  name: "My Video Overlays"
  resolution: [1920, 1080]
  framerate: 30

# Default settings applied to all overlays
defaults:
  font: "Inter"
  transition:
    type: fade
    duration: 0.25
  # Default styles applied to all overlays (can be overridden per-overlay)
  style:
    textShadow: "0 2px 10px rgba(0, 0, 0, 0.5)"

# Color theme
theme:
  primary: "#3B82F6"    # Blue
  secondary: "#1E293B"  # Dark slate
  text: "#F8FAFC"       # Light text
  accent: "#F59E0B"     # Amber

# Overlay definitions
overlays:
  # Title overlay - centered, fades in
  - id: intro-title
    type: title
    title: "Welcome"
    subtitle: "An Introduction"
    in: "0:01.000"
    out: "0:05.000"
    transition:
      in: fade
      out: fade
      duration: 0.5
    # Custom CSS styles (camelCase property names)
    style:
      fontWeight: 900
      letterSpacing: "0.05em"

  # Lower-third with sections - each line has independent timing
  - id: presenter
    type: lower-third
    title: "Speaker"  # Optional heading above sections
    in: "0:06.000"
    out: "0:12.000"
    position: bottom-left
    transition:
      in: fade
      out: fade
    sections:
      - text: "Your Name"
        in: "0:06.000"  # Fades in first
      - text: "Your Title"
        in: "0:06.500"  # Fades in 0.5s later
      - text: "Your Company"
        in: "0:07.000"  # Fades in 1s later

  # Callout with arrow - points to something on screen
  - id: highlight
    type: callout
    title: "Look here!"
    in: "0:15.000"
    out: "0:20.000"
    position: [800, 300]
    arrow: true
    arrow_target: [600, 400]

  # Code block - syntax highlighted
  - id: code-example
    type: code
    title: |
      function hello(name: string) {
        console.log(\`Hello, \${name}!\`);
      }
    in: "0:25.000"
    out: "0:35.000"
    position: center
    syntax: typescript

  # Parameter display - for showing values
  - id: param-display
    type: parameter
    label: "Threshold"
    value: "-18"
    unit: "dB"
    in: "0:40.000"
    out: "0:50.000"
    position: [100, 100]
`;

export async function initCommand(options: InitOptions): Promise<void> {
  if (options.output) {
    // Write to file
    fs.writeFileSync(options.output, sampleProject);
    console.log(`✅ Sample project file created: ${options.output}`);
    console.log("\nNext steps:");
    console.log(`  1. Edit ${options.output} with your overlay definitions`);
    console.log(`  2. Run: textoverlay validate ${options.output}`);
    console.log(`  3. Run: textoverlay render ${options.output} -o output.mov`);
  } else {
    // Output to stdout
    console.log(sampleProject);
  }
}
