#!/usr/bin/env python3
"""build probe (US3) — deterministic timeline construction + idempotency.

THROWAWAY spike code (see spike/README.md). Implements T013/T014:
  - T013: connect; import the synthetic fixture media (spike/fixtures/media/,
    generated by make_media.py) via MediaPool.ImportMedia; create a timeline
    named "Spike Timeline" (MediaPool.CreateEmptyTimeline); place a clip
    (MediaPool.AppendToTimeline); add a marker (Timeline.AddMarker).
  - T014: run the whole build sequence ``--runs`` times (default 2) and
    OBSERVE the re-run behavior (duplicate vs no-op vs error), recording it
    as a Finding regardless of outcome (idempotency evidence, FR-005). The
    spike never assumes idempotency — it records what actually happened.

Implements research.md R5: ImportMedia([paths]) -> CreateEmptyTimeline(name)
-> AppendToTimeline([clip]) -> timeline.AddMarker(...); run twice.

Every Resolve API call is guarded (try/except) — a missing/renamed method on
a given Resolve version is recorded as a gap (a Finding), never a crash
(contracts/probes.md shared contract; FR-014).

CLI contract (contracts/probes.md):
    python spike/probes/build.py [--project NAME] [--runs N]
    exit 0 = PASS (timeline+clip+marker created as specified on every run)
    exit 1 = observed-FAIL (unreliable creation)
    exit 2 = cannot-run (Resolve unreachable OR fixture media missing) —
             fails fast, never hangs, per FR-014.

The pure build-sequence helpers (guarded_call, run_build_once,
classify_idempotency, and the small finding-producing helpers they use) live
in build_support.py, kept importable and testable independently of this CLI
entrypoint.

Python 3.11-compatible syntax only.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Optional

# spike/ must be importable (this file lives at spike/probes/build.py) so the
# shared resolve_env / evidence modules can be reused as instructed.
SPIKE_ROOT = Path(__file__).resolve().parent.parent
if str(SPIKE_ROOT) not in sys.path:
    sys.path.insert(0, str(SPIKE_ROOT))

import evidence  # noqa: E402
import resolve_env  # noqa: E402
from evidence import EvidenceStrength, ProbeOutcome  # noqa: E402

from build_support import (  # noqa: E402
    TIMELINE_NAME,
    VIDEO_FIXTURE,
    AUDIO_FIXTURE,
    classify_idempotency,
    guarded_call,
    run_build_once,
)

PROBE_NAME = "build"

DEFAULT_PROJECT_NAME = "Resolve Spike Fixture"
DEFAULT_RUNS = 2


# --------------------------------------------------------------------------- #
# Fail-fast preconditions (T013/T014 CLI contract: exit 2, never hang)
# --------------------------------------------------------------------------- #


def check_fixture_media() -> Optional[str]:
    """Return an error message if fixture media is missing/empty, else None."""
    missing = [p for p in (VIDEO_FIXTURE, AUDIO_FIXTURE) if not (p.exists() and p.stat().st_size > 0)]
    if not missing:
        return None
    names = ", ".join(str(p) for p in missing)
    return (
        f"synthetic fixture media not found (or empty): {names}. "
        "Run `python spike/fixtures/make_media.py` first, then re-run this probe."
    )


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="build probe (US3): create a test timeline, import synthetic "
        "media, place a clip, add a marker; observe re-run (idempotency) behavior."
    )
    parser.add_argument(
        "--project",
        default=DEFAULT_PROJECT_NAME,
        help=f"Resolve project name to load/create (default: {DEFAULT_PROJECT_NAME!r})",
    )
    parser.add_argument(
        "--runs",
        type=int,
        default=DEFAULT_RUNS,
        help=f"number of times to run the build sequence (default: {DEFAULT_RUNS})",
    )
    return parser


def _write_cannot_run(reason_id: str, statement: str, evidence_text: str) -> None:
    provenance = evidence.build_provenance(probe=PROBE_NAME, result=ProbeOutcome.SKIPPED)
    findings = [
        evidence.finding(
            id=reason_id,
            statement=statement,
            strength=EvidenceStrength.NOT_FOUND,
            evidence=evidence_text,
        )
    ]
    out_path = evidence.write_probe_result(PROBE_NAME, provenance, findings, ProbeOutcome.SKIPPED)
    print(f"CANNOT-RUN: {statement}\n{evidence_text}")
    print(f"Findings written to {out_path}")


def main(argv: Optional[list[str]] = None) -> int:
    args = build_arg_parser().parse_args(argv)
    runs = max(args.runs, 1)

    # --- Fail-fast: fixture media must exist before we even try to connect. #
    media_error = check_fixture_media()
    if media_error:
        _write_cannot_run("build.fixture_media", "Synthetic fixture media is missing.", media_error)
        return 2

    # --- Fail-fast: Resolve must be reachable; never hang (FR-014). --------- #
    resolve = resolve_env.connect()
    if resolve is None:
        diagnosis = resolve_env.diagnose_connection_failure()
        _write_cannot_run(
            "build.connect", "Could not connect to a running DaVinci Resolve instance.", diagnosis
        )
        return 2

    ok, resolve_version, _ = guarded_call(getattr(resolve, "GetVersionString", None))
    resolve_version = resolve_version if ok and resolve_version else "unknown"

    ok, project_manager, err = guarded_call(getattr(resolve, "GetProjectManager", None))
    if not ok or project_manager is None:
        findings = [
            evidence.finding(
                id="build.project_manager",
                statement="Resolve.GetProjectManager() did not return a ProjectManager.",
                strength=EvidenceStrength.OBSERVED_FAIL,
                evidence=err or "GetProjectManager returned an empty/falsy result",
            )
        ]
        provenance = evidence.build_provenance(
            probe=PROBE_NAME, result=ProbeOutcome.FAIL, resolve_version=resolve_version
        )
        out_path = evidence.write_probe_result(PROBE_NAME, provenance, findings, ProbeOutcome.FAIL)
        print("FAIL: could not obtain a ProjectManager from the live Resolve connection.")
        print(f"Findings written to {out_path}")
        return 1

    findings: list[dict[str, Any]] = []
    run_results: list[dict[str, Any]] = []
    for run_index in range(1, runs + 1):
        result = run_build_once(project_manager, args.project, run_index)
        run_results.append(result)
        findings.extend(result["findings"])
        print(f"run {run_index}/{runs}: {'PASS' if result['ok'] else 'FAIL'}")

    # T014: idempotency Finding is recorded whenever there were >= 2 runs,
    # regardless of whether every individual run succeeded.
    if len(run_results) >= 2:
        findings.append(classify_idempotency(run_results))

    overall_ok = all(r["ok"] for r in run_results)
    overall_result = ProbeOutcome.PASS if overall_ok else ProbeOutcome.FAIL

    provenance = evidence.build_provenance(
        probe=PROBE_NAME, result=overall_result, resolve_version=resolve_version
    )
    out_path = evidence.write_probe_result(PROBE_NAME, provenance, findings, overall_result)

    print(
        f"{'PASS' if overall_ok else 'FAIL'}: timeline '{TIMELINE_NAME}' build sequence "
        f"across {runs} run(s)."
    )
    print(f"Findings written to {out_path}")
    return 0 if overall_ok else 1


if __name__ == "__main__":
    sys.exit(main())
